local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 10
  publish_frequency: 10
  rolling_window: true
  width: 3.0
  height: 3.0
  resolution: 0.05
  origin_x: 0
  origin_y: 0
  transform_tolerance: 4
  max_obstacle_height: 10
  min_obstacle_height: 0