#global_costmap:
#  update_frequency: 2.5
#  publish_frequency: 2.5
#  transform_tolerance: 2.1
#  rolling_window: true
#  width: 15
#  height: 15
#  origin_x: -7.5
#  origin_y: -7.5
#  resolution: 0.1
#  inflation_radius: 15

global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 0.1
  publish_frequency: 0.1
  rolling_window: true
  width: 20
  height: 20
  resolution: 0.1
  origin_x: 0
  origin_y: 0
  transform_tolerance: 4